//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUKUTAN.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KUKUTAN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   いんいちが,いち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いんにが,に に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いんさんが,さん に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いんしが,し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いんごが,ご に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _15 {
            get {
                return ResourceManager.GetString("15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いんろくが,ろく に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _16 {
            get {
                return ResourceManager.GetString("16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いんしちが,しち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _17 {
            get {
                return ResourceManager.GetString("17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いんはちが,はち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _18 {
            get {
                return ResourceManager.GetString("18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いんくが,く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _19 {
            get {
                return ResourceManager.GetString("19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   にいちが,に に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _21 {
            get {
                return ResourceManager.GetString("21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ににんが,し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _22 {
            get {
                return ResourceManager.GetString("22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   にさんが,ろく に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _23 {
            get {
                return ResourceManager.GetString("23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   に し が,はち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _24 {
            get {
                return ResourceManager.GetString("24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   に　ご,じゅう に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _25 {
            get {
                return ResourceManager.GetString("25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   に ろ く,じゅうに に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _26 {
            get {
                return ResourceManager.GetString("26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   に し ち,じゅうし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _27 {
            get {
                return ResourceManager.GetString("27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   に は ち,じゅうろく に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _28 {
            get {
                return ResourceManager.GetString("28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   に　く,じゅうはち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _29 {
            get {
                return ResourceManager.GetString("29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   さんいちが,さん に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _31 {
            get {
                return ResourceManager.GetString("31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   さんにが,ろく に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _32 {
            get {
                return ResourceManager.GetString("32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   さざんが,く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _33 {
            get {
                return ResourceManager.GetString("33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   さ ん し,じゅうに に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _34 {
            get {
                return ResourceManager.GetString("34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   さ ん ご,じゅうご に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _35 {
            get {
                return ResourceManager.GetString("35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   さぶろく,じゅうはち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _36 {
            get {
                return ResourceManager.GetString("36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   さんしち,にじゅういち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _37 {
            get {
                return ResourceManager.GetString("37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   さ ん ぱ,にじゅうし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _38 {
            get {
                return ResourceManager.GetString("38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   さ ん く,にじゅうしち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _39 {
            get {
                return ResourceManager.GetString("39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   しいちが,し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _41 {
            get {
                return ResourceManager.GetString("41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   し に が,はち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _42 {
            get {
                return ResourceManager.GetString("42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   し さ ん,じゅうに に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _43 {
            get {
                return ResourceManager.GetString("43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   し　し,じゅうろく に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _44 {
            get {
                return ResourceManager.GetString("44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   し　ご,にじゅう に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _45 {
            get {
                return ResourceManager.GetString("45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   し ろ く,にじゅうし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _46 {
            get {
                return ResourceManager.GetString("46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   し し ち,にじゅはち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _47 {
            get {
                return ResourceManager.GetString("47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   し　は,さんじゅうに に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _48 {
            get {
                return ResourceManager.GetString("48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   し　く,さんじゅうろく に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _49 {
            get {
                return ResourceManager.GetString("49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ごいちが,ご に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _51 {
            get {
                return ResourceManager.GetString("51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご　に,じゅう に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _52 {
            get {
                return ResourceManager.GetString("52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご さ ん,じゅうご に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _53 {
            get {
                return ResourceManager.GetString("53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご　し,にじゅう に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _54 {
            get {
                return ResourceManager.GetString("54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご　ご,にじゅうご に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _55 {
            get {
                return ResourceManager.GetString("55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご ろ く,さんじゅう に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _56 {
            get {
                return ResourceManager.GetString("56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご し ち,さんじゅうご に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _57 {
            get {
                return ResourceManager.GetString("57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご　は,しじゅう に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _58 {
            get {
                return ResourceManager.GetString("58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご っ く,しじゅうご に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _59 {
            get {
                return ResourceManager.GetString("59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ろくいちが,ろく に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _61 {
            get {
                return ResourceManager.GetString("61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ろ く に,じゅうに に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _62 {
            get {
                return ResourceManager.GetString("62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ろくさん,じゅうはち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _63 {
            get {
                return ResourceManager.GetString("63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ろ く し,にじゅうし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _64 {
            get {
                return ResourceManager.GetString("64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ろ く ご,さんじゅう に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _65 {
            get {
                return ResourceManager.GetString("65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ろくろく,さんじゅうろく に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _66 {
            get {
                return ResourceManager.GetString("66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ろくしち,しじゅうに に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _67 {
            get {
                return ResourceManager.GetString("67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ろ く は,しじゅうはち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _68 {
            get {
                return ResourceManager.GetString("68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ろ っ く,ごじゅうし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _69 {
            get {
                return ResourceManager.GetString("69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   しちいちが,しち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _71 {
            get {
                return ResourceManager.GetString("71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   し ち に,じゅうし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _72 {
            get {
                return ResourceManager.GetString("72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   しちさん,にじゅういち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _73 {
            get {
                return ResourceManager.GetString("73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   し ち し,にじゅうはち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _74 {
            get {
                return ResourceManager.GetString("74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   し ち ご,さんじゅうご に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _75 {
            get {
                return ResourceManager.GetString("75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   しちろく,しじゅうに に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _76 {
            get {
                return ResourceManager.GetString("76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   しちしち,しじゅうく に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _77 {
            get {
                return ResourceManager.GetString("77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   し ち は,ごじゅうろく に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _78 {
            get {
                return ResourceManager.GetString("78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   し ち く,ろくじゅうさん に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _79 {
            get {
                return ResourceManager.GetString("79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はちいちが,はち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _81 {
            get {
                return ResourceManager.GetString("81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   は ち に,じゅうろく に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _82 {
            get {
                return ResourceManager.GetString("82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はちさん,にじゅうし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _83 {
            get {
                return ResourceManager.GetString("83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   は ち し,さんじゅうに に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _84 {
            get {
                return ResourceManager.GetString("84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   は ち ご,しじゅう に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _85 {
            get {
                return ResourceManager.GetString("85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はちろく,しじゅうはち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _86 {
            get {
                return ResourceManager.GetString("86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はちしち,ごじゅうろく に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _87 {
            get {
                return ResourceManager.GetString("87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   は っ ぱ,ろくじゅうし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _88 {
            get {
                return ResourceManager.GetString("88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   は っ く,しちじゅうに に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _89 {
            get {
                return ResourceManager.GetString("89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   くいちが,く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _91 {
            get {
                return ResourceManager.GetString("91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   く　に,じゅうはち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _92 {
            get {
                return ResourceManager.GetString("92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   く さ ん,にじゅうしち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _93 {
            get {
                return ResourceManager.GetString("93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   く　し,さんじゅうろく に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _94 {
            get {
                return ResourceManager.GetString("94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   く　ご,しじゅうご に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _95 {
            get {
                return ResourceManager.GetString("95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   く ろ く,ごじゅうし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _96 {
            get {
                return ResourceManager.GetString("96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   く し ち,ろくじゅうさん に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _97 {
            get {
                return ResourceManager.GetString("97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   く　は,しちじゅうに に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _98 {
            get {
                return ResourceManager.GetString("98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   く　く,はちじゅういち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _99 {
            get {
                return ResourceManager.GetString("99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.IO.MemoryStream に類似した型 System.IO.UnmanagedMemoryStream のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream BUBU {
            get {
                return ResourceManager.GetStream("BUBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.IO.MemoryStream に類似した型 System.IO.UnmanagedMemoryStream のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream CBC {
            get {
                return ResourceManager.GetStream("CBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.IO.MemoryStream に類似した型 System.IO.UnmanagedMemoryStream のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream CBC1 {
            get {
                return ResourceManager.GetStream("CBC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   11,いんいちが,いち
        ///12,いんにが,に
        ///13,いんさんが,さん
        ///14,いんしが,し
        ///15,いんごが,ご
        ///16,いんろくが,ろく
        ///17,いんしちが,しち
        ///18,いんはちが,はち
        ///19,いんくが,く
        ///21,にいちが,に
        ///22,ににんが,し
        ///23,にさんが,ろく
        ///24,に し が,はち
        ///25,に　ご,じゅう
        ///26,に ろ く,じゅうに
        ///27,に し ち,じゅうし
        ///28,に は ち,じゅうろく
        ///29,に　く,じゅうはち
        ///31,さんいちが,さん
        ///32,さんにが,ろく
        ///33,さざんが,く
        ///34,さ ん し,じゅうに
        ///35,さ ん ご,じゅうご
        ///36,さぶろく,じゅうはち
        ///37,さんしち,にじゅういち
        ///38,さ ん ぱ,にじゅうし
        ///39,さ ん く,にじゅうしち
        ///41,しいちが,し
        ///42,し に が,はち
        ///43,し さ ん,じゅうに
        ///44,し　し,じゅうろく
        ///45,し　ご,にじゅう
        ///46,し ろ く,にじゅうし
        ///47,し し ち,にじゅはち
        ///48,し　は,さんじゅうに
        ///49,し　く,さんじゅうろく
        ///51,ごいちが,ご
        ///52,ご　に,じゅう
        ///53 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string kakeyomi {
            get {
                return ResourceManager.GetString("kakeyomi", resourceCulture);
            }
        }
    }
}
